### ISSUE TITLE
[A6] - Tokens with more than 18 decimals are not supported

### ISSUE THREAD

**Issue by grok13** [Gravita-Protocol/Gravita-SmartContracts#121]
Tokens with more than 18 decimals are not supported, based on the SafetyTransfer library (outside the audit scope).

<pre class="prettyprint">function decimalsCorrection(address _token, uint256 _amount)
   	 internal
   	 view
   	 returns (uint256)
    {
   	 if (_token == address(0)) return _amount;
   	 if (_amount == 0) return 0;

   	 uint8 decimals = ERC20Decimals(_token).decimals();
   	 if (decimals &lt; 18) {
   		 return _amount.div(10**(18 - decimals));
   	 }

   	 return _amount; // Dedaub: more than 18 not supported correctly!
    }</pre>

<p>
We do not recommend trying to address this, as it may introduce other complexities for very little practical benefit. Instead, we recommend just being aware of the limitation.

**Comment by 0xfornax** [comment]
Acknowledged. We don't plan to support tokens with more than 18 decimals.
