### ISSUE TITLE
[A10] - Anachronisms

### ISSUE THREAD

**Issue by grok13** [Gravita-Protocol/Gravita-SmartContracts#125]
The codebase exhibits some old code patterns (which we do not recommend fixing, since they directly mimick the Liquity trusted code):
<ul>

<li>The use of assert for condition checking (instead of require/if->revert). (Some of the asserts have been replaced, but not all.)

<li>The use of SafeMath instead of relying on Solidity 0.8.* checks.

**Comment by 0xfornax** [comment]
Acknowledged. We'll discuss changes in the code patterns. Keeping unchanged for now per the recommendation.
