### ISSUE TITLE
`permit` breaks if `block.chainid` changes on a fork

### ISSUE THREAD

**Issue by rotcivegaf** [Gravita-Protocol/Gravita-SmartContracts#204]
### Affected smart contract

- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/Dependencies/ERC20Permit.sol#L28
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/DebtToken.sol#L9
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/GRVT/GRVTToken.sol#L6

### Description

The `block.chainid` could change in the future as a result of a fork breaking the `permit` function

### Attack scenario

The `block.chainid` of ethereum it's `1` but if there is a fork where this changes the `permit` function it would use an incorrect DOMAIN_SEPARATOR breaking this function

### Recommendation

Look: [`permit` breaks if `block.chainid` changes on a fork](https://github.com/Gravita-Protocol/Gravita-SmartContracts/pull/221)

Also, can use the [**draft-ERC20Permit.sol** of Openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.8.3/contracts/token/ERC20/extensions/draft-ERC20Permit.sol) or directly the [**ERC20.sol** of Solmate](https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC20.sol)

**Comment by 0xfornax** [comment]
We appreciate the submission but this is a known issue previously submitted here[ https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/16](https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/16)
