### ISSUE TITLE
Missing validation in latestRoundData

### ISSUE THREAD

**Issue by WelToHackerLand** [Gravita-Protocol/Gravita-SmartContracts#211]
### Title
Missing validation in latestRoundData

### Severity 
Medium 

### Affected smart contract
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/PriceFeed.sol#L245-L256

### Description 
Price of `_token` is fetched by calling `lastestRoundData()` from chainlink oracle. The contract `PriceFeed.sol` has a several checks with the response returned from the oracle in `_isValidResponse()` function. But it still doesn't have a check for the `answeredInRound` parameter.

According the [chainlink doc](https://docs.chain.link/data-feeds/historical-data#getrounddata-return-values) 
> `answeredInRound`: The combination of `aggregatorAnsweredInRound` and `phaseId`. `aggregatorAnsweredInRound`: The round the answer was updated in. You can check `answeredInRound` against the current `roundId`. If `answeredInRound` is less than `roundId`, the answer is being carried over. If `answeredInRound` is equal to `roundId`, then the answer is fresh.

So there is a potential scenario where the chainlink oracle can return a stale data, and the protocol doesn't validate the param `answeredInRound` which can lead to the incorrect price returned. 

### Impact 
Incorrect price returned from chainlink oracle 

### Recommendation
Require `answeredInRound == roundId`.

**Comment by 0xfornax** [comment]
Thank you for your report. While Liquity, Vesta, and Yeti were the protocols we used as a starting point, we have noticed that none of them consider the 'answeredInRound' value, relying instead on the 'updatedAt' timestamp to check for data staleness. We appreciate your suggestion and have taken note of it. We will consider adding a second validity check to our platform.
