### ISSUE TITLE
Lack of check for round completeness in chainlink oracle integration leads to stale / outdated price

### ISSUE THREAD

**Issue by ArnieGod** [Gravita-Protocol/Gravita-SmartContracts#213]
##Title
Lack of check for round completeness in chainlink oracle integration leads to stale / outdated price. MEDIUM

## Vulnerability detail 

In the current implementation,

the oracle integration make sure that if the price is stale, an fallback (prev valid oracle price can be used)

However, the logic to validate if the price is stable may has issue:

```solidity
bool isValidResponse = _isFeedWorking(_currResponse, _prevResponse) &&
	!_isPriceStale(_currResponse.timestamp) &&
	!_isPriceChangeAboveMaxDeviation(oracle.maxDeviationBetweenRounds, _currResponse, _prevResponse);
```

we are calling isValidResponse

```solidity
function _isValidResponse(FeedResponse memory _response) internal view returns (bool) {
	return
		(_response.success) &&
		(_response.roundId > 0) &&
		(_response.timestamp > 0) &&
		(_response.timestamp <= block.timestamp) &&
		(_response.answer > 0);
}
```

the validation only check if the round Id > 0,

chainlink latestRoundData() return answeredInRound as well

```solidity
try _priceAggregator.latestRoundData() returns (
			uint80 roundId,
			int256 answer,
			uint256, /* startedAt */
			uint256 timestamp,
			uint80 /* answeredInRound */
		) {
			// If call to Chainlink succeeds, return the response and success = true
			response.roundId = roundId;
			response.answer = answer;
			response.timestamp = timestamp;
			response.success = true;
		} ;
```

there is no check for round completeness and the parameter answeredInRound is not used.

According to Chainlink's documentation, this function does not error if no answer has been reached but returns 0 or outdated round data. The external Chainlink oracle, which provides index price information to the system, introduces risk inherent to any dependency on third-party data sources. For example, the oracle could fall behind or otherwise fail to be maintained, resulting in outdated data being fed to the index price calculations. Oracle reliance has historically resulted in crippled on-chain systems, and complications that lead to these outcomes can arise from things as simple as network congestion.

Chainlink documentation:
https://docs.chain.link/docs/historical-price-data/#historical-rounds

## Impact

If there is a problem with chainlink starting a new round and finding consensus on the new value for the oracle (e.g. chainlink nodes abandon the oracle, chain congestion, vulnerability/attacks on the chainlink system) consumers of this contract may continue using outdated stale data (if oracles are unable to submit no new round is started).

This could lead to stale prices and wrong price return value, or outdated price.

As a result, the functions rely on accurate price feed might not work as expected, sometimes can lead to fund loss. The impacts vary and depends on the specific situation like the following:

- incorrect liquidation
some users could be liquidated when they should not
no liquidation is performed when there should be

- wrong price feed
causing inappropriate loan being taken, beyond the current collateral factor
too low price feed affect normal borrow

## Recommended Mitigation Steps

We recommend add the check

```solidity
function _isValidResponse(FeedResponse memory _response) internal view returns (bool) {
	return
		(_response.success) &&
		(_response.roundId > 0) &&
		(_response.timestamp > 0) &&
		(_response.timestamp <= block.timestamp) &&
		(_response.answeredInRound >= response.roundID) // fix here
		(_response.answer > 0);
}
```

basically this logic:

```solidity
   function getOraclePrice(IAggregatorV3 _priceFeed, int192 _maxPrice, int192 _minPrice) public view returns (uint256 ) {
        (
            uint80 roundID,
            int signedPrice,
            /*uint startedAt*/,
            uint timeStamp,
            uint80 answeredInRound
        ) = _priceFeed.latestRoundData();
        //check for Chainlink oracle deviancies, force a revert if any are present. Helps prevent a LUNA like issue
        require(signedPrice > 0, "Negative Oracle Price");
        require(timeStamp >= block.timestamp - HEARTBEAT_TIME , "Stale pricefeed");
        require(signedPrice < _maxPrice, "Upper price bound breached");
        require(signedPrice > _minPrice, "Lower price bound breached");
        require(answeredInRound >= roundID, "round not complete");

        uint256 price = uint256(signedPrice);
        return price;
    }
```

note the line of code:

```solidity
 require(answeredInRound >= roundID, "round not complete");

**Comment by 0xfornax** [comment]
We appreciate your report, this is a duplicate of issue #211. We appreciate your suggestion and have taken note of it. We will consider adding a second validity check to our platform.
