### ISSUE TITLE
Timelock contract execution delay can be ineffective and not usable if the execution delay is more than grace period

### ISSUE THREAD

**Issue by ArnieGod** [Gravita-Protocol/Gravita-SmartContracts#214]
# Title 
Timelock contract execution delay can be ineffective and not usable if the execution delay is more than grace period.
Medium

# Vulnerability detail

Timelock contract execution can queue transaction and let the admin execute governane paramter changes while give user sufficient time to prepare for the change.

```solidity
uint public constant GRACE_PERIOD = 14 days;
uint public constant MINIMUM_DELAY = 2 days;
uint public constant MAXIMUM_DELAY = 15 days;
```

However, the grace period is 14 days and minimum day is 2 days while maximum delay is 15 days, the delay is between 2 days and 15 days 

```solidity
	modifier isValidDelay(uint256 _delay) {
		if (_delay < MINIMUM_DELAY) {
			revert Timelock__DelayMustExceedMininumDelay();
		}
		if (_delay > MAXIMUM_DELAY) {
			revert Timelock__DelayMustNotExceedMaximumDelay();
		}
		_;
	}
```

However, if the maximum delay is more than 14 days (between 14 days and 15 days), then the timelock contract execution delay is not effective.

# Impact

When executing a timelock transaction

```solidity
if (block.timestamp > eta + GRACE_PERIOD) {
	revert Timelock__TxExpired();
}
```

if the execution delay is more than 14 days, for example, 14.5 days, the pending transaction can be never executed because the transaction expires in grace period.

# Recommended Fix

We recommend the protocol change the max delay below grace period to avoid accidental denial of service of the execution delay setting.

**Comment by 0xfornax** [comment]
We appreciate the submission. We'll implement an additional check to avoid mistakes when creating timelock transactions.
