### ISSUE TITLE
try catch code in PriceFeed.sol#_fetchCurrentResponse can be gas bomb and drain the user gas

### ISSUE THREAD

**Issue by ArnieGod** [Gravita-Protocol/Gravita-SmartContracts#217]
# Title
try catch code in PriceFeed.sol#_fetchCurrentResponse can be gas bomb and drain the user gas
HIGH

# Vulnerability detail

Let us look into the current in Oracle below

```solidity
	function _fetchCurrentFeedResponse(AggregatorV3Interface _priceAggregator)
		internal
		view
		returns (FeedResponse memory response)
	{
		try _priceAggregator.decimals() returns (uint8 decimals) {
			// If call to Chainlink succeeds, record the current decimal precision
			response.decimals = decimals;
		} catch {
			// If call to Chainlink aggregator reverts, return a zero response with success = false
			return response;}
		try _priceAggregator.latestRoundData() returns (
			uint80 roundId,
			int256 answer,
			uint256, /* startedAt */
			uint256 timestamp,
			uint80 /* answeredInRound */
		) {
			// If call to Chainlink succeeds, return the response and success = true
			response.roundId = roundId;
			response.answer = answer;
			response.timestamp = timestamp;
			response.success = true;
		} catch {
			// If call to Chainlink aggregator reverts, return a zero response with success = false
			return response;
		}
	}
```

the try statement is meant to use a prev valid prie is the current price revert

However, the code can waste dramatic amound of gas and make user lose fund (at the repetitive use of gas)

we need to take a close look at two try catch

```solidity
try _priceAggregator.decimals() returns (uint8 decimals) {
		// If call to Chainlink succeeds, record the current decimal precision
		response.decimals = decimals;
	} catch {
		// If call to Chainlink aggregator reverts, return a zero response with success = false
		return response;}
```

However, the function call .decimals does not revert even in depracted chainlink, for example, free feel to call .decimals function in a deprecated price in chainlink polygon.

a valid oracle is 0x443C5116CdF663Eb387e72C688D276e702135C87 while the deprecated oracle is 

0x2E5B04aDC0A3b7dB5Fd34AE817c7D0993315A8a6

https://polygonscan.com/address/0x2e5b04adc0a3b7db5fd34ae817c7d0993315a8a6#readContract

the .decimal just return 0, but 0 should not be considered as a valid response, 

if the decimal return 0, then there is no need to call the following latestRoundData, the response should be returned instead.

also calling latestRoundData when it is reverting can consume a lot of gas

again you can call latestRoundData

https://polygonscan.com/address/0x2e5b04adc0a3b7db5fd34ae817c7d0993315a8a6#readContract

it revert in 

```solidity
Error: Returned error: execution reverted
```

which consume a lot of gas and keep calling reverted transaction consume a lot of gas from user.

# Impact

latestRoundData is still being called over and over again even though it is guranteed to revert, leads to large gas consumption and make user lose ETH gas.

Putting severe as high because this leads to theft and large waste of gas and user would be discouraged to see their gas fund is drained so fast.

# Recommended Fix

We recommend the protocol just return response if the decimal is 0 and not keeping call latestRoundData to waste gas.

```solidity
		try _priceAggregator.decimals() returns (uint8 decimals) {
		  if(decimals == 0) { return response} // return early
			// If call to Chainlink succeeds, record the current decimal precision
			response.decimals = decimals;
		} catch {
			// If call to Chainlink aggregator reverts, return a zero response with success = false
			return response;}
```

**Comment by 0xfornax** [comment]
We appreciate the submission. The competition rules define that gas griefing  (making users overpay for gas) is a medium severity.
