### ISSUE TITLE
lack of validation in _calcEthPrice and division before multiplication decimal scaling leads to incorrect oracle price

### ISSUE THREAD

**Issue by ArnieGod** [Gravita-Protocol/Gravita-SmartContracts#219]
# Title 
lack of validation in _calcEthPrice and division before multiplication decimal scaling leads to incorrect oracle price
HIGH

# Vulnerability detail

In the current implementation of the oracle integration, the are case that needs to current ETH price to USD

```solidity
uint256 scaledPrice = _scalePriceByDigits(uint256(_currResponse.answer), _currResponse.decimals);
		if (oracle.isEthIndexed) {
			// Oracle returns ETH price, need to convert to USD
			scaledPrice = _calcEthPrice(scaledPrice);
		}
```

we are calling

```solidity
function _calcEthPrice(uint256 ethAmount) internal returns (uint256) {
	uint256 ethPrice = fetchPrice(address(0));
	return ethPrice * ethAmount / 1 ether;
}
```

while the _scalePriceByDigits code is:

```solidity
	function _scalePriceByDigits(uint256 _price, uint256 _answerDigits) internal pure returns (uint256 price) {
		if (_answerDigits >= TARGET_DIGITS) {
			// Scale the returned price value down to Gravita's target precision
			price = _price / (10**(_answerDigits - TARGET_DIGITS));
		} else if (_answerDigits < TARGET_DIGITS) {
			// Scale the returned price value up to Gravita's target precision
			price = _price * (10**(TARGET_DIGITS - _answerDigits));
		}
	}
```

basically the line of code:

```solidity
return ethPrice * ethAmount / 1 ether;
```

bother ethPrice and ethAmount are derived from _scalePriceByDigit

then the code becomes

```
(price1 / (10 ** (TARGET_DIGIER - answerDigit2)) * price2 / (10 ** (TARGET_DIGIT - answerDigit2))) / 1e18
```

this formula use division before manipulation, which incurs heavy precision loss and truncate the amount, and can even leads to 0 price (which is clearly wrong)

most chainlink price oracle return 8 decimals, which there are chainlink oracle price return 18 decimals.

let us say the price1 return 8 decimals and price2 return 8 deicmals.

price1 from oracle is 200,0000,0000  (200 * 10 ** 8) 
price2 from oracle is 1000,0000,0000 (100 * 10 ** 8)

if we use the current formula

```solidity
(price1 / (10 ** (TARGET_DIGIER - answerDigit1) = (200,00000000) / (10 ** (18 - 8)) = 2
```

and

```solidity
(price2 / (10 ** (TARGET_DIGIER - answerDigit2) = (1000,00000000) / (10 ** (18 - 8)) = 10
```

and (2 * 10) / (1e18) is easily truncate to 0

then the scaledPrice is wrongly return to 0 and there is no code check if place to check the scaledPrice is not 0.

```solidity
	if (oracle.isEthIndexed) {
			// Oracle returns ETH price, need to convert to USD
			scaledPrice = _calcEthPrice(scaledPrice);
		}
```

# Impact

Impact is severe, wrong oracle can lead to force liquidation or wrong repaid or redemption which make user lose fund.

# Recommended Fix

Avoid division before multiplication in price oracle when deriving the ETH index price and validate that the scaledPrice is not 0

**Comment by gbirckan** [comment]
Thank you for your submission. We have thoroughly reviewed the problem you reported but unfortunately were unable to replicate it using the suggested values provided. We would like to reiterate that, as stated in our guidelines, a high severity report must include a pull request that demonstrates the problem with at least one test, and if possible, a proposed fix. Regrettably, your submission did not meet these requirements.
