### ISSUE TITLE
SortedVessels linked list could have more element than `maxSize`

### ISSUE THREAD

**Issue by mojito-auditor** [Gravita-Protocol/Gravita-SmartContracts#223]
## Affected codes
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/SortedVessels.sol#L61

## Description
In SortedVessels.Data struct, there is a `maxSize` param which is the maximum size of the linked list and `size` param which is the current size of the list. As the name could suggest, the list should always have `size <= maxSize`. However, currently there is no check for `maxSize` is done in function `insert()`. 
```solidity
function insert(
	address _asset,
	address _id,
	uint256 _NICR,
	address _prevId,
	address _nextId
) external override {
	IVesselManager vesselManagerCached = vesselManager;
	_requireCallerIsBOorVesselM(vesselManagerCached);
	_insert(_asset, vesselManagerCached, _id, _NICR, _prevId, _nextId);
}

function _insert(
	address _asset,
	IVesselManager _vesselManager,
	address _id,
	uint256 _NICR,
	address _prevId,
	address _nextId
) internal {
	Data storage assetData = data[_asset];
        ...
        }
}
```

## Impact
As a result, the linked list could have the size larger than maximum size, which breaks the constraint of the contract. 

## Recommendation
Consider adding check `isFull()` when inserting new element as this function is already implemented in the contract
```solidity
/*
* @dev Checks if the list is full
*/
function isFull(address _asset) public view override returns (bool) {
	return data[_asset].size == data[_asset].maxSize;
}
```

**Comment by 0xfornax** [comment]
We are not enforcing a max size on the vessel list as made explicit here (https://github.com/Gravita-Protocol/Gravita-SmartContracts/pull/188/commits/f4fe51af370ecb33df3a11154a1f1b66dc422566). Nowhere in the code we try to iterate through the list, so we should not have gas issues related to the list size. The isFull function and max size were left behind but can also be removed. This means that there is no issue related to them other than a bit of gas spent with the unused code.
