### ISSUE TITLE
Unchecked RoundID and Timestamp leads the data may be staled and unCompleted Round timestamp and _isPriceStale() check can be bypassed  

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#224]
**Affected Smart contracts**
PriceFeed.sol

**Impact**
_isPriceStale() can be bypassed and roundId may be staled .

**Severity**
Medium

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L245-L256

**Reference :-**
https://docs.chain.link/docs/historical-price-data/#historical-rounds

**Description :-**
In _fetchCurrentFeedResponse() function use to get current feed response from ChainLink oracle but there is no proper check ,for whether the received roundId is staled or uncompleted timestamp round [0] leads to _isPriceStale() check can be bypass. _fetchCurrentFeedResponse() function fetch feed response and direclty copy to response variable struct . In [_isValidResponse](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L176) checks roundId  but it's not enough .And in [_isPriceStale()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L165) directly get timestamp from feed and subtract from block.timestamp which can be bypass like below scenario ,timestamp can be zero if round not completed . 

**Example**

return block.timestamp - _priceTimestamp > RESPONSE_TIMEOUT;
= 1777777 - 0 > 14400
= 1777777 > 14400

**Recommedation :-**
Add below check in _fetchCurrentFeedResponse() function 

require(answeredInRound >= roundId, 'stale price');
require(timestamp != 0, 'round not complete');

**Comment by 0xfornax** [comment]
We appreciate the report, but there is a limitation defined on the competition vault excluding "Attacks related to incorrect data supplied by third-party oracles".

**Comment by pavankv241** [comment]
Hai @0xfornax  , yes data from oracle is out of scope. But impact of this report is no check in [_isPriceStale()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L165) function check can be bypass. [_isPriceStale()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L165) will give bool without checking whether _priceTimestamp is zero or not. If _priceTimestamp is zero for any other reason [_isPriceStale()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/PriceFeed.sol#L165) will return true bool .

**Comment by 0xfornax** [comment]
Hey @pavankv241, the steps you mention for us to use

require(answeredInRound >= roundId, 'stale price');
require(timestamp != 0, 'round not complete');

are listed on the docs related to getting historical rounds (https://docs.chain.link/docs/historical-price-data/#historical-rounds). Please note that we are not using the feature to fetch historical rounds, but instead we get the latest round.
