### ISSUE TITLE
An attacker can make an reentrancy attack of the `asset` it's an **ERC777**

### ISSUE THREAD

**Issue by rotcivegaf** [Gravita-Protocol/Gravita-SmartContracts#227]
### Affected smart contract

- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L515-L519
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/CollSurplusPool.sol#L82
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/DefaultPool.sol#L60
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L181
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L333
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L347
- https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/StabilityPool.sol#L783

### Description

The mentioned functions could be perform a transfer where the asset is an `ERC777` which could lead to a reentrancy attack as **ERC777** asset call the receiver/sender with [`tokensReceived`/`tokensToSend`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b438cb695a1ac520cee6678610b161b1d5df4d9c/contracts/token/ERC777/ERC777.sol#L454-L503) functions

### Attack scenario

Although the **Active Pool** contract protects itself from reentrancy attacks, contracts that use this function are not protected

1. In the **DefaultPool** the internal function [`sendAssetToActivePool`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/DefaultPool.sol#L49) who is called by the **VesselManager** in [`_movePendingVesselRewardsToActivePool`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L493) function leaving this one vulnerable too

2. In the **CollSurplusPool** the internal function [`claimColl`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/CollSurplusPool.sol#L67)

3. In the **BorrowerOperations** the internal function [`_activePoolAddColl`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L509) who is used in [`openVessel`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L113) and [`_moveTokensFromAdjustment`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L485)(used by [`_adjustVessel`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L270))

4. In the **FeeCollector** contract there are many functions that make these attacks possible:

- [`handleRedemptionFee`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L178) who is used by the **VesselManager** in [`finalizeRedemption`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L314) function leaving this one vulnerable too
- The [`_collectFee`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L326) internal function who is used by [`increaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L83), [`collectFees`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L150), [`_decreaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L191)(used by [`decreaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L97) and [`closeDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L108)) and [`_closeExpiredOrLiquidatedFeeRecord`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L282)(used by [`liquidateDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L140), [`_decreaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L191))
- The [`_refundFee`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L341) internal function who is used by [`_decreaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L191)(used by [`decreaseDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L97) and [`closeDebt`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManager.sol#L108))
Leaving the contract with several points of attacks
For example in the [L287-L288](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L287-L288) first call the `_collectFee` and then delete the `feeRecords`, giving the possibility to manipulate the `feeRecords`

5. In the **StabilityPool** contract the internal function `StabilityPool` use in [`provideToSP`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/StabilityPool.sol#L295) and [`withdrawFromSP`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/StabilityPool.sol#L324) functions, where the first function have a `nonReentrant` modifier and the `withdrawFromSP` function does not, enabling the possibility of a reentrancy attack on the last one, attacking the [totalColl.amounts](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/StabilityPool.sol#L788)

>> Compound and its forks have suffered several attacks of this style
>> Look: [Some lessons of reentrancy attacks](https://medium.com/amber-group/preventing-re-entrancy-attacks-lessons-from-history-c2d96480fac3)

### Recommendation

Add `nonReentrant` guard in the functions mentioned
#277

**Comment by 0xfornax** [comment]
We won't work with ERC-777. Also, this issue was previously reported here https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/108 "The protocol should not be used with collateral tokens that perform callbacks to the sender of tokens. E.g., ERC 777 tokens have this behavior and they are well-known as reentrancy death traps."
