### ISSUE TITLE
_closeVessel()  will revert if VesselOwners have only one owner . 

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#229]
**Affected Smart contracts**
VesselManager.sol

**Impact**
If VesselOwner have one owners address in dynamic array of VessolOwners mapping _closeVessel() will revert .

**Severity**
Medium

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManager.sol#L602

**Description :-**
There is no restriction to [openVessel()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol#L172) with single owner   . But while closing vessel [_closeVessel()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManager.sol#L602) will revert if same vessel have single owner address in [VesselOwners](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManager.sol#L89) will revert because of below check 
``if (VesselOwnersArrayLength <= 1 || sortedVessels.getSize(_asset) <= 1)`` 

scenario :- 
address[] owners = ['address1'] ;  

owners.length   // will return 1 
owners index is ZERO .

So if Vessel have single address in array of  [VesselOwners](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManager.sol#L89) will get revert . In SortedVessels.sol  [_insert()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/SortedVessels.sol#L149) will add 1 to asset size so it can pass in  VesselManager.sol _closeVessel() check but VesselOwners mappings have dynamic array if it contain single owner address .   There is no mention docs also vessel should have two single owners . VesselOwners mappings only access to when add owner in openVessel() and remove owner when closing vessel.  

**Recommedation :-**
Add restriction in openVessel() only OR remove check of VesselOwner.length<=1 OR 

`if (sortedVessels.getSize(_asset) <= 1)`

OR 
 
mapping(address => address) public VesselOwners;  // single vessel single owner .

**Comment by 0xfornax** [comment]
We appreciate the submission but this is a design choice. Note that the error is specifically telling us the revert reason is having a single vessel VesselManager__OnlyOneVessel
