### ISSUE TITLE
AdminContract.addNewCollateral() is not looking for the decimals from the ERC20 contract and a wrong combination of ERC20 contract + decimals will be allowed

### ISSUE THREAD

**Issue by nicobevilacqua** [Gravita-Protocol/Gravita-SmartContracts#235]
AdminContract.addNewCollateral() can be called with an ERC20 such as USDT (which has 6 decimals) with a different decimal configuration (like 18 decimals) breaking the conversion.

**Comment by 0xfornax** [comment]
We appreciate the submission. Considering this is an admin function, we added a check to avoid mistakes.

**Comment by 0xfornax** [comment]
@nicobevilacqua could you reach out on Discord and provide your wallet for the prize?
