### ISSUE TITLE
`AdminContract.setCCR` does not validate that CCR should be greater than MCR

### ISSUE THREAD

**Issue by aviggiano** [Gravita-Protocol/Gravita-SmartContracts#237]
### `AdminContract.setCCR` does not validate that CCR should be greater than MCR

`AdminContract.setCCR` does not validate that CCR should be greater than MCR. If an incorrect value is set, this may cause all vessels to become liquidatable.

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/AdminContract.sol#L255

### Description

`AdminContract.setCCR` does not validate that CCR should be greater than MCR. If an incorrect value is set, this may cause all vessels to become liquidatable.

### Recommendation

Update `safeCheck` to prevent the admin from setting CCR lower than MCR

```diff
diff --git a/contracts/AdminContract.sol b/contracts/AdminContract.sol
index 79fb747..ff4c145 100644
--- a/contracts/AdminContract.sol
+++ b/contracts/AdminContract.sol
@@ -252,7 +252,7 @@ contract AdminContract is IAdminContract, ProxyAdmin {
 		public
 		override
 		shortTimelockOnly
-		safeCheck("CCR", _collateral, newCCR, 1010000000000000000, 10000000000000000000) /// 101% - 1000%
+		safeCheck("CCR", _collateral, newCCR, collateralParams[_collateral].mcr, 10000000000000000000) /// MCR - 1000%
 	{
 		CollateralParams storage collParams = collateralParams[_collateral];
 		uint256 oldCCR = collParams.ccr;

```

**Comment by 0xfornax** [comment]
We appreciate the submission, but the CCR can assume a value lower than the minimum. For instance, we want the blUSD collateral in a way that it is not liquidatable on the system (assuming a stable price of $1 for each blUSD).  We could set the MCR as 1.02 and CCR as 1.01. This means that users would only be able to go as low as 1.02 and the TCR would never be lower than 1.02, and would never trigger the recovery mode.
