### ISSUE TITLE
PriceFeed: Incorrect fallback price mechanism leading to protocol DoS

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#238]
The PriceFeed contract intends to use a fallback price mechanism. When the latest ChainLink price is stale, the `_processFeedResponses` function tries to fallback to the stored `priceRecord.scaledPrice` value. But the implementation of this function is broken. 

### Affected smart contract

- PriceFeed
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/PriceFeed.sol#L123-L147

### Description

In the `_processFeedResponses` function, the `_currResponse` is validated against staleness.
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/PriceFeed.sol#L123-L125
In case the `_currResponse` is stale the `isValidResponse` boolean turns out to be `false`. Hence the `else` block is executed.
```solidity
		if (isValidResponse) {
			...
		} else {
			...
			PriceRecord memory priceRecord = priceRecords[_token];
			if (_isPriceStale(priceRecord.timestamp)) {
				revert PriceFeed__FeedFrozenError(_token);
			}
			return priceRecord.scaledPrice;
		}
```
It should be noted that the `else` block also checks the staleness of previously recorded `priceRecord` value, if `priceRecord` value is stale the txn is reverted.

This is where the issue lies. Chainlink oracles work with incremental `roundIds`. Round id `n + 1` always comes after round id `n` with regards to timestamps. 

Hence when the `_currResponse` is stale, it is almost certain that the previously recorded `priceRecord` will also be stale. And as the staleness check is also performed for `priceRecord` the `fetchPrice` call will get reverted. Essentially the code in the `else` will never get executed successfully when `_currResponse` is stale.

This issue causes DoS for the `fetchPrice` function. This function is used in other protocol functions like:
- BorrowerOperations.openVessel()
- BorrowerOperations.adjustVessel()
- BorrowerOperations.closeVessel()
- StabilityPool.withdrawFromSP()
- VesselManagerOperations.liquidateVessels()
- VesselManagerOperations.batchLiquidateVessels()
- VesselManagerOperations.redeemCollateral()

All these functions will suffer a DoS due to this bug.

Special attention should be given to the DoS of liquidation operations. As liquidations are crucial time sensitive operations for Gravita protocol, DoS of liquidations will lead to protocol solvency issues in case liquidations do not happen in timely manner.

Also to further alleviate the issue, the oracle configuration can only be updated by the timelock contract which has a minimum delay of two days. So DoS will happen until the oracle config is updated in the PriceFeed contract (minimum 2 days).

### Attack scenario
Consider this scenario:
- Chainlink report correct and fresh price `X` for a token, this valid price gets stored in `priceRecord`.
- Due to any possible reason, the latest price on Chainlink becomes stale (older than 4 hours).
- The `PriceFeed.fetchPrice` is called, due to a stale price from Chainlink the `isValidResponse` becomes `false`.
-  The PriceFeed tries to fallback upon the previously recorded `priceRecord` value. The `else` block is executed of `_processFeedResponses` function.
- The staleness check is performed again for `priceRecord` value which fails (reasons already explained)
- The `fetchPrice` call is reverted along with the parent call (like liquidation).

### Recommendation
Do not perform the same `RESPONSE_TIMEOUT` duration staleness check for both `_currResponse` and `priceRecord`.

There could be multiple mitigation paths here like:
- performing the `priceRecord` staleness check with much longer duration than `RESPONSE_TIMEOUT`
- omitting the staleness check for `priceRecord` (this could be risky)
- creating some other fallback mechanism like using some other fallback oracle than chainlink

**Comment by akshaysrivastav** [comment]
PR - #328

**Comment by gbirckan** [comment]
Thank you for your report. We appreciate your feedback and want to clarify some points. The Timelock for updating oracles was a deliberate design choice to prioritize the security of our system. While we acknowledge that a collateral type could be frozen for up to two days in rare and unpredictable scenarios, removing the timelock would introduce many more attack vectors. We need our users to be aware in advance of any changes to the oracle, which is why we have implemented this timelock. Therefore, it cannot be considered a DoS.

Regarding the second issue, we intended to have a second internal timeout after the oracle price went stale, where we would temporarily use a cached value until it timed out. However, you pointed out that this second grace period was not properly being carried out, and a second timeout counter was necessary. After discussing it internally, we have decided to keep the current implementation that only accepts a total of 4-hour delays. However, we will consider adding another fallback mechanism such as querying a second oracle for the price, possibly Tellor, to ensure the accuracy and reliability of our system. We appreciate your report, and we will continue to work towards improving our system while prioritizing security.

**Comment by akshaysrivastav** [comment]
Hey @gbirckan thanks for your response.
The timelock mechanism is not the actual bug here, it was just mentioned as an additional note which alleviates the core issue.

The core issue reported here is that the current fallback price mechanism is completely broken. Once the current price of chainlink goes stale the Gravita protocol enters a DoS state (including liquidations) which is a high risk situation. The exact attack was demonstrated in PR #328.

I hope you are understanding the severity of this bug. From your comment above it is not much clear whether you are considering this as a high severity bug or not. It will be very much appreciated if you can confirm that.
Thanks

**Comment by 0xfornax** [comment]
Greetings @akshaysrivastav! The current design has the intention to make operations revert if the price is stale. For this to be considered a DoS attack you would need to be able to make chainlink go stale, meaning this argument falls on the competition rule stating that submissions based on incorrect values from oracles are not eligible.
