### ISSUE TITLE
StabilityPool assumes collateral assets are in wrapped version, but AdminContract does not validate this assumption when adding a new collateral

### ISSUE THREAD

**Issue by aviggiano** [Gravita-Protocol/Gravita-SmartContracts#241]
### StabilityPool assumes collateral assets are in wrapped version, but AdminContract does not validate this assumption when adding a new collateral

[StabilityPool._sendGainsToDepositor](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/StabilityPool.sol#L782) assumes collateral assets are in wrapped version, but AdminContract does not validate this assumption when adding a new collateral with `AdminContract.addNewCollateral`. 

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/StabilityPool.sol#L782

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/AdminContract.sol#L153

### Description

Due to the nature of some LST, such as stETH, the balance of an address is not constant - it changes daily as staking rewards come in. This is what's known as a rebasable token. Because of that, transfering tokens may lead to a case where the whole balance can't be transferred from the account, while leaving the last [1 wei](https://docs.lido.fi/guides/steth-integration-guide/#1-wei-corner-case) on the sender's account. Because of that, it is recommended to use a wrapped version of stETH, which allows for easier integrations. 

Gravita is already aware of this issue and will support wstETH from the start. The problem is that `StabilityPool` assumes only wrapped versions are supported, while the `AdminContract` does not enforce this assumption, and only stores a `isWrapped` variable on the `collateralParams` mapping of assets.

If the admin adds a new collateral (e.g. `stETH`, the non-wrapped version), some funds will be lost on the `StabilityPool`.

### Attack scenario

1. The admin adds a new collateral that is a rebasing token (e.g. `stETH`). Even if `isWrapped` is set to `false`, the issue still exists
2. Some funds will be lost on `StabilityPool` when distributing rewards

### Recommendation

Modify `AdminContract.sol` to enforce wrapped collaterals only.

**Comment by 0xfornax** [comment]
We appreciate the report, but this attack considers an admin account adding unsupported collateral types which fall into the limitation "Attacks that require access to leaked private keys or trusted addresses".
