### ISSUE TITLE
`unstake` function is not compatible with tokens that implement a block list feature

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#246]
### Title 

`unstake` function is not compatible with tokens that implement a block list feature 

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/GRVT/GRVTStaking.sol#L118

### Description

Some tokens, for example USDC and USDT implement an admin controlled address block list. All transfers to a blocked address will revert.

### Attack scenario

Since the `unstake` functionality transfers the claimable tokens to the `msg.sender` address, the call will revert if such an address has claimable balance and is in the token's block list.

### Recommendation

Use the Pull over Push pattern to send tokens out of the contract in a revoke scenario.

**Comment by 0xfornax** [comment]
Thanks for the report! The GRVTStaking.sol contract is not on the scope of the competition.
