### ISSUE TITLE
Signature Malleability

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#247]
### Title

Signature Malleability

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/Dependencies/ERC20Permit.sol#L57

### Attack scenario

The function calls the Solidity `recover()` function directly to verify the given signatures. However, the `recover()` EVM opcode allows malleable (non-unique) signatures and thus is susceptible to replay attacks.
Although a replay attack seems not possible for this contract, I recommend using the battle-tested OpenZeppelin’s ECDSA library.

### Recommendation

Use the `ecrecover` function from OpenZeppelin’s ECDSA library for signature verification. (Ensure using a version > 4.7.3 for there was a critical bug >= 4.1.0 < 4.7.3).

**Comment by 0xfornax** [comment]
Thanks for the report! We are already using the suggested ECDSA library.
