### ISSUE TITLE
No error message is returned

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#249]
### Title

No error message is returned for require

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/GRVT/GRVTStaking.sol#L76

### Description

Consider adding a error description, in order to stick to the best practises

### Recommendation

Add failure message in require

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques of best practices would not be eligible.
