### ISSUE TITLE
[STR-02M] Insecure Conversion of Amount

### ISSUE THREAD

**Issue by 0xfornax** [Gravita-Protocol/Gravita-SmartContracts#25]
## STR-02M: Insecure Conversion of Amount

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Mathematical Operations](/appendix/finding-types#mathematical-operations) | <img class="o-severity o-major" src="https://omniscia.io/report-assets/major.png" /> | [SafetyTransfer.sol:L22](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/bfa97cb37dc0e2927e75b36753585140f25a26dd/contracts/Dependencies/SafetyTransfer.sol#L22) |

### Description:

The [`SafetyTransfer::decimalsCorrection`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/bfa97cb37dc0e2927e75b36753585140f25a26dd/contracts/Dependencies/SafetyTransfer.sol#L12-L26) function is utilized to assess **how much funds should be transferred**. As such, it is possible to specify a value that will truncate to `0` when "normalized" to the token's decimal accuracy, permitting deposits of zero funds to acquire a non-zero effective value in the protocol.

### Impact:

It is currently possible to trick functions such as [`BorrowerOperations::_activePoolAddColl`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/bfa97cb37dc0e2927e75b36753585140f25a26dd/contracts/BorrowerOperations.sol#L524-L535) to perform a zero-value transfer yet credit a non-zero deposit value to the caller, significantly compromising the operational integrity of the protocol.

### Example:

```solidity
function decimalsCorrection(address _token, uint256 _amount)
	internal
	view
	returns (uint256)
{
	if (_token == address(0)) return _amount;
	if (_amount == 0) return 0;

	uint8 decimals = ERC20Decimals(_token).decimals();
	if (decimals < 18) {
		return _amount.div(10**(18 - decimals));
	}

	return _amount;
}
```

### Recommendation:

We advise the code to mandate that `_amount` modulo (`%`) the divisor (i.e. `10**(18 - decimals)`) equals zero, preventing impossible deposit values from being specified.

**Comment by grok13** [comment]
Unrelated, but we may want to remove the following as we are not using pure ETH
`if (_token == address(0)) return _amount;`
