### ISSUE TITLE
Non-Conforming `ERC20` Tokens Not Recoverable

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#250]
### Title 

Non-Conforming `ERC20` Tokens Not Recoverable

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/GRVT/GRVTStaking.sol#L111

### Attack scenario

There are tokens that do not return a value on success, which will cause the call to revert, even when the transfer would have been successful. This means that those tokens will be stuck forever and not be recoverable.
Someone accidentally transfers USDT, one of the most commonly used ERC20 tokens, to the contract. Because USDT’s transfer does not return a boolean, it will not be possible to recover those tokens and they will be stuck forever.

### Recommendation

It's recommended to use OpenZeppelin’s `safeTransferFrom` instead of `transferFrom`.

**Comment by 0xfornax** [comment]
We appreciate the submission but the protocol doesn't aim to support non conforming ERC-20s.
