### ISSUE TITLE
Misleading name is used

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#251]
### Title

Misleading name is used

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/AdminContract.sol#L263-L266

### Description

`setActive` function name gives a wrong assumption that collateral can only be activated, which is totally incorrect.

### Recommendation

Replace the function name `setActive` with `changeCollateralStatus`
Replace the parameter name `_active` with `_status`
Replace the props `CollateralParams.active` with `CollateralParams.status`

```solidity
 function changeCollateralStatus(address _collateral, bool _status) public onlyOwner { 
 	CollateralParams storage collParams = collateralParams[_collateral]; 
 	collParams.status = _status;
 } 
```

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques to best practices would not be eligible, therefore we will not address the naming choices of admin-only functions
(though something like "setIsCollateralActive" might indeed sound better).
