### ISSUE TITLE
`require()` should be used instead of `assert()`

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#252]
```solidity
299: assert(
300:    msg.sender == _borrower || (address(stabilityPool) == msg.sender &&  _assetSent > 0 && _debtTokenChange == 0)
301:);
```

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques of best practices would not be eligible.

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques to best practices would not be eligible.
