### ISSUE TITLE
File is missing NatSpec

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#253]
Following the Solidity Style Guide sections, try to write as detailed comments as possible to make it easier for auditors, developers or other technical guys to understand the purpose of each particular feature and its parameters.

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/GRVT/CommunityIssuance.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/GRVT/GRVTStaking.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/GRVT/GRVTToken.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/GRVT/LockedGRVT.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/ActivePool.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/AdminContract.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/AdminContract.sol
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques of best practices would not be eligible.
