### ISSUE TITLE
Mixing alternative ways to perform checks is discouraged

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#254]
### Title

Mixing alternative ways to perform checks is discouraged

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/AdminContract.sol#L91-L107

### Description

In `safeCheck` modifier both `require` and custom error are used. Consider using a consistent way to perform checks. Using custom error is the better approach since it is the more often used one in the contract and has a large number of positives anyway.

### Recommendation

Replace `require` with `if - custom error`

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that critiques to best practices would not be eligible.
