### ISSUE TITLE
Vessels from inactive collateral asset can still be adjusted

### ISSUE THREAD

**Issue by aviggiano** [Gravita-Protocol/Gravita-SmartContracts#258]
### Vessels from inactive collateral asset can still be adjusted

`AdminContract` defines an [`active`](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/AdminContract.sol#L152) parameter for each one of the collateral types.  `BorrowerOperations` verifies this parameter on `openVessel` before creating new vessels, but not on other operations that adjust the vessel. If a collateral is deactivated, for any reason, borrowers can still perform operations such as removing collateral or debt token.

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol#L126

### Description

The `active` parameter from the `AdminContract` is read on `BorrowerOperations.openVessel`, which has a `require(contractsCache.adminContract.getIsActive(_asset))` allowing only vessels to be open with active collaterals.

However, this requirement is not enforced on other functions that call `_adjustVessel`.

As a result, borrowers are still able to manage their vessels even if the collateral is deactivated.

### Attack scenario

1. The admin sets one of the collateral assets as not `active` anymore, for any reason.
2. Borrowers are still able to perform operations on their vessels. For example, they can call `withdrawColl` and `withdrawDebtTokens`. This might not be intended, as the collateral is set to not `active`

### Recommendation

Include the same `require` on all `_adjustVessel` operations.

**Comment by 0xfornax** [comment]
We appreciate the submission but that is the intended behavior as the platform doesn't want to freeze assets in case they're no longer supported.
