### ISSUE TITLE
Users are unable to withdraw their collateral and fully repay the loan

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#259]
## Summary

During the recovery mode, users with normal ICR are unable to repay the debt and get the collateral back. So this means that repayments are paused while liquidations are possible. This would allow vessels to be liquidated but not repaying their debt. If the protocol wants to pause repayments, it should also pause the liquidations despite the mode it's in.

## Vulnerability Detail

Although it seems that it's a special measure that's designed by the protocol to recover the system ("pure debt repayment"), it should be a huge concern that users are unable to repay their debt and get their collateral back. This should be considered as freezing of funds, even if it's a short period of time. Protocol is supposed to work as expected in any case, even in such exceptional and rare as recovery mode.

## Impact

High-risk vulnerability because the users funds are frozen for uncertain period of time and the protocol will not implement its functionality properly as expected. It'll also stop incentivizing new users from interacting with protocol in recovery mode because they'll know that for that period of time their collateral will be locked. Even though there is a non-fee mechanism for new debt in recovery mode, the lock of collateral is a serious concern. 

## Code Snippet

In BorrowerOperations.sol, in the closeVessel() function there is a check to make sure that the protocol is not in the recovery mode making it impossible to fully repay the debt.

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L394

Users can just use repayDebtTokens() function for "pure debt repayment", but they are not getting their collateral back as adjustVessel() also makes sure that the collWithdrawal is impossible during the recovery mode:

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L338

## Tool used

Manual Review

## Recommendation

Custom logic should be added to make users be able to withdraw their collateral because some users will not be able to do it even if their ICR is far away from CCR. So I suggest adding some functionality to allow users with low-risk debt be able to repay the loans during the recovery mode and get the collateral.

**Comment by 0xfornax** [comment]
We appreciate the submission but this is how the recovery mode was designed and that is the correct behavior.
