### ISSUE TITLE
In VesselManagerOperations too big _vesselArray can cause state of DoS.

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#260]
## Summary

Looping over an unbounded array.

## Vulnerability Detail

In VesselManagerOperations.sol, we have the user-provided _vesselArray parameter in batchLiquidateVessels() function. The function only checks whether the length is equal to 0. The totalDebt, in its turn, can be not necessarily very big but consist of very small amounts of vessels to liquidate. The function later calls internal _getTotalFromBatchLiquidate_RecoveryMode and _getTotalFromBatchLiquidate_NormalMode where it loops over this array vessels which has the potential to become too big and too expensive to execute.

## Impact

Medium-risk vulnerability (but also can be considered as high because in the case of batchLiquidateVessels() DoS one of the key functionalities of the protocol - liquidations - will be broken). Function can become too expensive for users to execute. 

## Code Snippet

batchLiquidateVessels():

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L155

Internal _getTotalsFromBatchLiquidate_NormalMode() and _getTotalsFromBatchLiquidate_RecoveryMode():

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/VesselManagerOperations.sol#L470
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/VesselManagerOperations.sol#L544

## Tool used

Manual Review

## Recommendation

To create some mitigation logic such as limiting max array size such as "require(arrayLength < arrayLimit)"

**Comment by rodiontr** [comment]
> We appreciate the submission! We considered this issue as low severity as there is no attack causing loss of user funds or a gas griefing. The user would choose how many vessels to liquidate and could check if the gas would fit the limit.

But what about the cases where there are too much vessels to liquidate, especially in fluctuated market conditions, user can just decide to liquidate them all and break the function. Because no entity is trusted. That's a classic example of looping over an unbounded array and i think it's a medium severity by definition. What's your opinion?

**Comment by 0xfornax** [comment]
> But what about the cases where there are too much vessels to liquidate, especially in fluctuated market conditions, user can just decide to liquidate them all and break the function. Because no entity is trusted. That's a classic example of looping over an unbounded array and i think it's a medium severity by definition. What's your opinion?

We initially considered it as low severity as the user is choosing the number of vessels to liquidate. No attacker is imposing this gas cost on users if they selected a number that is too big. That said, we have changed the code to enforce a maximum batch size and will consider this issue as medium severity.
