### ISSUE TITLE
_activePoolAddColl() may be fail because no approve before safeTransferFrom()

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#261]
**Affected Smart contracts**
BorrowerOperations.sol

**Impact**
openVessel() and _activePoolAddColl() can be fail.

**Severity**
Medium because user cannot deposit thier LST collateral .

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol#L515

Description :-
 Gravita Protocol accepts LST tokens as collateral but in  [_activePoolAddColl()](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol#L509) direclty calls safeTransferFrom() of [SafeERC20Upgradeable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/utils/SafeERC20Upgradeable.sol)
which call amount from msg.amount .But some LST like WETH require approve() before safeTransferFrom(). If user try to deposit LST tokens (WETH and others) which expects approve before safeTransferFrom(), openVessel() and  _activePoolAddColl() may get fail . Because WETH token expect approve before transferFrom() or safeTransferFrom().

Recommedation :-
Add below code in _activePoolAddColl()

approve(address spender, uint256 amount);
IERC20Upgradeable(_asset).safeTransferFrom(
			msg.sender,
			address(_activePool),
			SafetyTransfer.decimalsCorrection(_asset, _amount)
		);
approve(address spender, uint256 0);

**Comment by 0xfornax** [comment]
We appreciate the submission, but the flow for calling functions that require previous approval is to first have the approval transaction submitted by the user instead of trying to do both at the same transaction.
