### ISSUE TITLE
Possible memory corruption due to uncontrolled dynamic array parameter in internal _getTotalsFromLiquidateVesselsSequence_NormalMode and _getTotalsFromLiquidateVesselsSequence_RecoveryMode functions

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#262]
## Summary

If you have a memory array inside of internal function as a parameter of user-supplied length - this could subsequently cause memory corruption and out-of-gas issues. 

## Vulnerability Detail

In the VesselManagerOperations.sol, when you call the internal _getTotalsFromLiquidateVesselsSequence_NormalMode and _getTotalsFromLiquidateVesselsSequence_RecoveryMode functions and pass an array of vessel addresses as a memory parameter, a complete copy of these addresses is created within the function. if this array becomes huge and you can't remove (pop) elements from it, this becomes a serious concern as more and more elements are added.

## Impact

Can potentially be a high vulnerability and break one of the critical functions for the protocol.

## Code Snippet

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/VesselManagerOperations.sol#L474
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/VesselManagerOperations.sol#548

## Tool used

Manual Review

## Recommendation

Limiting maximum array size is considered a good practice.

**Comment by 0xfornax** [comment]
We appreciate the submission. Duplicate of https://github.com/Gravita-Protocol/Gravita-SmartContracts/issues/260
