### ISSUE TITLE
Protocol doesn't have any logic to handle fee-on-transfer ERC20 tokens

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#266]
## Summary

The protocol doesn't handle ERC20 tokens  that take fee on transfer operations.

## Vulnerability Detail

This could lead to some serious unexpected behavior making protocol think that the borrower has more collateral than he actually deposited (for example).

## Impact

Medium-risk vulnerability.

## Code Snippet / Attack Scenario

Consider the following situation:

1. Alice opens a vessel with 100 tokens of fee-on-transfer collateral and the protocol transfers the tokens to the activePool thinking it's 100 tokens but the actual amount that was sent is 98 tokens (as an example, if the fee is 2%).
2. As the actual amount is 98 tokens, ICR and NICR will be miscalculated for this particular borrower making his position bigger than it is. Therefore, it can lead to some unexpected behavior, for example, the borrower will not be liquidated if ICR < MCR even if it is.

openVessel() and _assetAmount
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L115

calculations of ICR and NICR:

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L152
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/BorrowerOperations.sol#L153

## Tool used

Manual Review

## Recommendation

Integration of such tokens will require special handling on the integrating protocol side (pre-calculating the fee, so the _assetAmount argument passed has the correct value)

**Comment by 0xfornax** [comment]
We appreciate the report. The protocol doesn't aim to support fee-on-transfer ERC-20s.
