### ISSUE TITLE
Protocol does have any handling of ERC20 tokens that сan have balance modifications outside of transfers

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#267]
## Summary

The protocol doesn't consider any operations with tokens that can have arbitrary modifications outside of transfers (such as Ampleforth-like rebasing tokens or tokens with implemented mint / burn / airdrop functionality).

## Vulnerability Detail

Unexpected behavior and some operations can possibly fail.

## Impact

Medium-risk vulnerability.

## Code Snippet / Attack Scenario

Consider the following situation:

1. Alice sends 100 tokens as collateral to his debt and they are sent to the ActivePool.sol.
2. The ActivePool fixes the balance of her collateral as 100 tokens.
3. However, due to rebasing happened, Alice now has 80 tokens as the collateral but the balance is 100 tokens.
4. Now if she's fully repaying her position, the ActivePool will try to send her 100 tokens and make her balance zero. However, in this case, it will fail because assetsBalances[_asset] - _amount will be <0. This is just one of the cases where using such tokens could lead to unexpected behavior. 

## Tool used

Manual Review

## Recommendation

Create some custom logic or tell in the documentation that the protocol doesn't support such ERC20 tokens as collateral. Or when rebasing tokens go down in value, you should have a method to update the cached balances accordingly, based on the balance held

**Comment by 0xfornax** [comment]
We appreciate the report. The protocol doesn't aim to support rebalancing tokens.

**Comment by rodiontr** [comment]
> We appreciate the report. The protocol doesn't aim to support rebalancing tokens.

The protocol supports stETH as collateral but stETH balance is updated daily due to reflect staking rewards earned. It's recommended to use then wstETH that doesn't update the balance. So it can be still considered a big as it will calculate and fix the collateral balance but it will increase over time.

**Comment by 0xfornax** [comment]
We are using wstETH. If you want to interact with our Goerli deployment at goerli.gravitaprotocol.com you'll see the collateral list we're launching with.

**Comment by 0xfornax** [comment]
Also, here's the twitter announcement of the protocol onboarding wstETH
https://twitter.com/gravitaprotocol/status/1657065380559331329
