### ISSUE TITLE
`FeeCollector.collectFees` can set the `FeeRecord.from` value to invalid timestamps

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#270]
The `FeeCollector.collectFees` function updates the `FeeRecord.from` value without validating the current timestamp. This lets anyone change the `from` value for any borrower. The `from` value can even be set to before `MIN_FEE_DAYS` and after `to`.

### Affected smart contract

- FeeCollector
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L165-L167

### Description

The `FeeCollector.collectFees` is an open function which can be invoked by anyone. This function updates the `FeeRecord.from` value to current `block.timestamp` value. 

```solidity
	function collectFees(address[] calldata _borrowers, address[] calldata _assets) external override {
		...
		uint256 NOW = block.timestamp;
		for (uint256 i = 0; i < borrowersLength; ) {
			...
			uint256 expiredAmount = _calcExpiredAmount(sRecord.from, sRecord.to, sRecord.amount);
			if (expiredAmount == 0) {
				continue;
			}
			uint256 updatedAmount = sRecord.amount - expiredAmount;
			sRecord.amount = updatedAmount;
			sRecord.from = NOW;      // <------- BUG
			_collectFee(borrower, asset, expiredAmount);
			emit FeeRecordUpdated(borrower, asset, NOW, sRecord.to, updatedAmount);
			unchecked {
				i++;
			}
		}
	}
```

For any borrower the function can be invoked after the `FeeRecord.to` timestamp which essentially sets the `FeeRecord.from` value to a timestamp greater than `FeeRecord.to`. Ideally the `from` timestamp should never be greater than `to` but this invariant is not honoured by the `collectFees` function. 

Similarly the `collectFees` function can also be executed before the `MIN_FEE_DAYS` has passed. This will set the  `FeeRecord.from` value to a timestamp less than `original from + 7 days`.

Both these scenarios may result in reverting of crucial FeeCollector operations (like `collectFees`). But due to the issue reported in #269 the calls reverts due to infinite loop.

### Attack scenario

New test file was created and ran using `yarn test path-to-file`
```javascript
const { expect } = require("chai");
const { BigNumber } = require("ethers");
const { ethers } = require("hardhat");
const {
    time,
} = require("@nomicfoundation/hardhat-network-helpers")

const { parseUnits, parseEther, formatUnits, formatEther } = ethers.utils

describe("FeeCollectorAudit", async () => {
    let feeCollector, debtToken, assetToken, admin, user, treasury;

    const MIN_FEE_SECONDS = 7 * 86400;
    const FEE_EXPIRATION_SECONDS = 175 * 86400;
    const MIN_FEE_FRACTION = parseEther('0.038461538')

    beforeEach(async () => {
        [admin, user, treasury] = await ethers.getSigners()

        const ERC20MockFactory = await hre.ethers.getContractFactory("ERC20Mock");
        debtToken = await ERC20MockFactory.deploy("Debt Mock", "DDD", 18);
        assetToken = await ERC20MockFactory.deploy("Asset Moch", "AAA", 18);

        const FeeCollectorFactory = await hre.ethers.getContractFactory("FeeCollector");
        feeCollector = await FeeCollectorFactory.deploy();
        await feeCollector.setAddresses(
            admin.address,
            admin.address,
            ethers.constants.AddressZero,
            debtToken.address,
            treasury.address,
            false
        )
    })

    const getCurrentBlockTS = async () => (await ethers.provider.getBlock(await ethers.provider.getBlockNumber())).timestamp;
    const bn = (num) => BigNumber.from(num)

    const calcFeeAndAmount = (debtAmount) => {
        const fee = bn(debtAmount).mul(MIN_FEE_FRACTION).div(parseEther('1'))
        const amount = bn(debtAmount).sub(fee);
        return [fee, amount]
    }

    it.only("Bug: collect: `from` is set after `to` ", async () => {
        const depositAmount = parseEther('1000')
        await debtToken.mint(feeCollector.address, depositAmount)
        await feeCollector.increaseDebt(user.address, assetToken.address, depositAmount)

        await time.increase(200 * 86400);

        await feeCollector.collectFees([user.address], [assetToken.address])

        expect(await debtToken.balanceOf(treasury.address)).to.eq(depositAmount)
        expect(await debtToken.balanceOf(feeCollector.address)).to.eq(0)
        expect(await debtToken.balanceOf(user.address)).to.eq(0)

        const feeRecord = await feeCollector.feeRecords(user.address, assetToken.address)
        expect(feeRecord.from).to.be.gt(feeRecord.to);

        await expect(feeCollector.collectFees([user.address], [assetToken.address])).to.be.reverted
    })

    it.only("Bug: collect: `from` is set before the `MIN_FEE_DAYS (attack case)` ", async () => {
        const depositAmount = parseEther('1000')
        await debtToken.mint(feeCollector.address, depositAmount)
        await feeCollector.increaseDebt(user.address, assetToken.address, depositAmount)

        // reverts due to infinite loop issue
        await expect(feeCollector.collectFees([user.address], [assetToken.address])).to.be.reverted

    })
})
```

### Recommendation

Consider setting the `FeeRecord.from` value as per the current duration of the debt. The `from` value should always be greater than `MIN_FEE_DAYS` limit and always be smaller than or equal to `FeeRecord.to`.

**Comment by 0xfornax** [comment]
We appreciate the report. Please notice that _calcExpiredAmount() will return 0 when "from" is in the future (meaning record is still within MIN_FEE_DAYS), so the theory that "collectFees function can also be executed before the MIN_FEE_DAYS has passed" is not valid as per the "if" on line 161. The other theory is about invoking the function after the "to" timestamp, which makes it so _calcExpiredAmount() will return the full amount (expiredAmount will be equal to record.amount), and in that case the record.amount will be set to zero on line 165 - in such scenario, we no longer care about "from" value as there are no more fees to decay.

**Comment by akshaysrivastav** [comment]
Still the unwanted setting of `from` and `to` values to incorrect timestamps is a bug, isn't it? This incorrect state update should be prevented.

**Comment by 0xfornax** [comment]
"From" and "to" are only used to calculate the expired fee. If there's no error in the calculation there is no bug.
