### ISSUE TITLE
FeeCollector: Owner has the privilege to cause DoS for all crucial contract operations

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#272]
The `owner` of `FeeCollector` contract has the privilege to forcefully revert calls to all functions of this contract.

### Affected smart contract

- FeeCollector
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/FeeCollector.sol#L326-L339

### Description

The FeeCollector inherits `OwnableUpgradeable` and thus has owner privileges. 

The contract is also responsible for transferring the expired debt of users as fee to the Gravita `treasury` or `grvtStaking` contract. This done using the `_collectFee` function. This function invoked in all crucial operations of FeeCollector contract such as:
- increaseDebt
- decreaseDebt
- closeDebt
- liquidateDebt
- collectFees

It should be noted that `owner` has the right to set the `routeToGRVTStaking` and `grvtStaking` parameters.

As per the implementation is `DebtToken` contract, it inherits OpenZeppelin's ERC20 contract. The OZ's ERC20 prevents all token transfers to the `0x00` address by reverting the entire transaction.

Due to the combination of all above things, the admin gets the power to forcefully stop all operations of FeeCollector contract by setting the `grvtStaking` address to `0x00` value. This can be done by invoking the `setGRVTStakingAddress` function.

```solidity
	function setGRVTStakingAddress(address _grvtStakingAddress) external onlyOwner {
		grvtStaking = IGRVTStaking(_grvtStakingAddress);
		emit GRVTStakingAddressChanged(_grvtStakingAddress);
	}
```

All the above mentioned functions of FeeCollector contracts are used in various Gravita contracts (like BorrowingOperations). DoS of FeeCollector will mean DoS of entire Gravita protocol (including liquidations).

It is well understood that centralisation risk is out of scope for this audit but the issue I explained is concerning so it needed to be reported. Moreover the [medium article](https://hatsfinance.medium.com/get-ready-for-a-new-audit-competition-coming-to-hats-finance-up-to-105k-in-prizes-8bbcf3d51034) for this audit only mentions that `"Centralization risks” that are known and/or explicitly coded into the protocol (e.g. an administrator can upgrade crucial contracts and steal all funds)` are OOS. But the issue I am reporting certainly does not fall into the known or explicitly coded category.

The risk due to this issue is huge while the fix to resolve it is very small.

### Attack scenario

Consider this scenario:
- Gravita protocol gets deployed on mainnet.
- The `owner` of `FeeCollector` sets `0x00` address as the `grvtStaking` parameter.
- Suddenly all user transactions to Gravita protocol will start reverting resulting in a complete DoS.

### Recommendation

Consider validating the `grvtStaking` addresses to not be `0x00` when `routeToGRVTStaking` flag is enabled.
```solidity
	function setGRVTStakingAddress(address _grvtStakingAddress) external onlyOwner {
		if (routeToGRVTStaking && address(_grvtStakingAddress) == address(0)) {
			revert FeeCollector__InvalidGRVTStakingAddress();
		}
		grvtStaking = IGRVTStaking(_grvtStakingAddress);
		emit GRVTStakingAddressChanged(_grvtStakingAddress);
	}
```

**Comment by 0xfornax** [comment]
We appreciate the report but the rules are clear that centralization risks or operations from privileged accounts would not be eligible for the competition.

**Comment by akshaysrivastav** [comment]
The threat reported here is not an obvious centralization risk, the report shows an edge case which can cause protocol level DoS and proposes a fix to resolve the issue.

As per the guidelines:
> “Centralization risks” that are known and/or explicitly coded into the protocol (e.g. an administrator can upgrade crucial contracts and steal all funds)
Attacks that require access to leaked private keys or trusted addresses

The reported scenario neither seems to be known nor explicitly coded. 

The purpose of having Timelocks in Gravita is to minimize the impact of sudden configuration changes to the protocol which may impact user's funds. The bug reported here exposes a scenario which can severily impact protocol operations. Hence I hope you can reconsider this report @0xfornax

**Comment by 0xfornax** [comment]
> > Attacks that require access to leaked private keys or trusted addresses
Owner is a trusted address and you're describing an attack that requires access to the owner address.

Regardless, we are willing to add more checks to reduce the level of trust in the owner address.
