### ISSUE TITLE
Unsafe external call can lead to a gas-griefing attack in TimeLock.sol and no check if the target contract is an existing account

### ISSUE THREAD

**Issue by rodiontr** [Gravita-Protocol/Gravita-SmartContracts#273]
## Summary

When we implement low-level call() method, we get the returnData which will automatically be copied to memory. Allocation in memory is very expensive as if the payload is huge.

## Vulnerability Detail

If a target function implements fallback() function, it can send a huge payload to the relayer (msg.sender) that will have to pay a lot of gas for copying this returnData to memory. Also, when implementing such low-level calls it's necessary to make sure that the target account is an existing account because by default the call() opcode will return true even if the account doesn't exist.

## Impact

Medium-risk vulnerability.

## Code Snippet / Attack Scenario

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/v0.1/contracts/Timelock.sol#L173

## Tool used

Manual Review

## Recommendation

It's recommended to implement low-level assembly call which will not copy the returnData:

bool success;
assembly {
       success := call(3000, target, value, 0, 0, 0, 0)
}
and it's better to use OZ Address library to make such calls or check if the target account doesn't exist before the call.

**Comment by 0xfornax** [comment]
We appreciate the submission but the timelock operations are admin only, so admins are responsible for making calls to safe contracts. The rules are clear that centralization risks or operations from privileged accounts would not be eligible for the competition.

**Comment by rodiontr** [comment]
that's me
