### ISSUE TITLE
The `LocalVariables_AssetBorrowerPrice:_borrower` it's never used

### ISSUE THREAD

**Issue by rotcivegaf** [Gravita-Protocol/Gravita-SmartContracts#276]
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManagerOperations.sol#L785
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/Interfaces/IVesselManagerOperations.sol#L117

### Description

This parameter it's never used

### Recommendation

Remove this one, look #275

**Comment by 0xfornax** [comment]
We appreciate the submission for the gas saving.
