### ISSUE TITLE
Permanent loss of cbETH funds

### ISSUE THREAD

**Issue by saxenism** [Gravita-Protocol/Gravita-SmartContracts#278]
# Permanent loss of cbETH funds

## Would cbETH be used in the protocol?

Since Gravita protocol is entirely based on liquid staking tokens (LSTs) as collateral for functioning and coinbase Ether (cbETH) is one of the most dominant LST currently it is almost a certainty that cbETH would be accepted as a collateral in the Gravita protocol.

We can also see the team's intention of accepting cbETH in the protocol from [their website](https://www.gravitaprotocol.com/) with this screenshot:

![](https://user-images.githubusercontent.com/32522659/235344617-347ebb45-b89d-4fb9-be7d-34b311cb54ea.png)

With this, we can establish quite reliably that Gravita intends to use `cbETH` as one of their LST collaterals.

## What is the issue with cbETH

Well, the very first issue with `cbETH` is that it is Coinbase Ether and Coinbase is a private, centralized organization and therefore can make unilateral decisions. 

Secondly, Coinbase in particular has had quite a few run-ins with the Feds and it would be quite reasonable to assume that they'll have decently strong regulatory pressure from different government agencies.

Thirdly, if you inspect the [codebase for cbETH](https://vscode.blockscan.com/ethereum/0xBe9895146f7AF43049ca1c1AE358B0541Ea49704), you will realize that they maintain a blacklist of addresses that cannot interact with their cbETH tokens. And, as you can expect the decision to put different people on the blacklist is completely up to Coinbase and everybody should assume that they can be put on that list for no apparent reason too.

## How is Gravita affected

**Gravita is severly affected** by the presence of this blacklist.

Gravita currently has absolutely no failsafe mechanisms to combat any of it's borrower, staker address being put into the blacklist suddenly. The even worse case scenario would be if one or more of Gravita protocol's contract address itself is put in the cbETH blacklist.

### Example1: `activePool` gets blacklisted

An important aspect of the core functionality of the `DefaultPool` is to be able to send funds to the `activePool`, which it does via `DefaultPool.sendAssetToActivePool()`. Here is the function for reference:

```solidity
function sendAssetToActivePool(address _asset, uint256 _amount) external override callerIsVesselManager {
    address activePool = activePoolAddress; // cache to save an SLOAD

    uint256 safetyTransferAmount = SafetyTransfer.decimalsCorrection(_asset, _amount);
    if (safetyTransferAmount == 0) {
        return;
    }

    uint256 newBalance = assetsBalances[_asset] - _amount;
    assetsBalances[_asset] = newBalance;

    IERC20Upgradeable(_asset).safeTransfer(activePool, safetyTransferAmount);
    IDeposit(activePool).receivedERC20(_asset, _amount);

    emit DefaultPoolAssetBalanceUpdated(_asset, newBalance);
    emit AssetSent(activePool, _asset, safetyTransferAmount);
}
```

So, now if the `activePool` address is suddenly blacklisted the transfer would start failing and add to this problem the fact that **there is no admin function to change the activePool address**, this means this function is bricked permanently for all `cbETH` assets.

### Example2: `treasuryAddress` gets blacklisted

Similar to Example 1, in `FeeCollector.sol` too there is no option to change the `treasuryAddress` in an adverse scenario where the `treasuryAddress` is added to the blacklist. 

This basically implies that if the`treasuryAddress` is ever blacklisted, the protocol would **not be able to collect fees** or handle redemptions in terms of `cbETH` tokens.

### Example3: StabilityPool user is blacklisted after depositing in the pool

If you take a look at the function `StabilityPool._sendGainsToDepositor`, you will realise that it will be impossible to distribute the `cbETH` rewards to a staker if they were suddenly blacklisted. This means that those funds will forever be stuck in the protocol contract as there is no alternative function to withdraw those funds by the protocol admins.

Here is the function for reference purposes:

```solidity
function _sendGainsToDepositor(
    address _to,
    address[] memory assets,
    uint256[] memory amounts
) internal {
    uint256 assetsLen = assets.length;
    require(assetsLen == amounts.length, "StabilityPool: Length mismatch");
    for (uint256 i = 0; i < assetsLen; ) {
        uint256 amount = amounts[i];
        if (amount == 0) {
            unchecked {
                i++;
            }
            continue;
        }
        address asset = assets[i];
        // Assumes we're internally working only with the wrapped version of ERC20 tokens
        IERC20Upgradeable(asset).safeTransfer(_to, amount);
        unchecked {
            i++;
        }
    }
    totalColl.amounts = _leftSubColls(totalColl, assets, amounts);
}
```

## Recommended Mitigation Steps

1. Every contract that is calling an external contract and the address of those external contracts are being set in functions with the `initializer` modifier, need to have another `onlyOwner` admin function to change any of those addresses later on.

2. Stakers who get blacklisted should either be allowed to give alternate addresses that are eligible to withdraw on behalf of the blacklisted staker or their should be an `onlyOwner` admin function which can collect any such stuck funds from the protocol.

## Conclusion

With the above explanation and examples, I hope I was able to convince the protocol devs that in the current state, the Gravita protocol is quite ill-equipped to handle any blacklisting action from Coinbase regarding `cbETH`.

I hope it is clear that necessary changes are required so that the protocol has an alternative course of action in adverse scenarios.

**Comment by 0xfornax** [comment]
We appreciate your report. While we initially considered cbETH as a collateral type we would support, we have decided that it will not be available on our platform at launch. If, in the future, we decide to include a censorable collateral, we will add additional mechanics in upcoming contract upgrades to circumvent such limitations
