### ISSUE TITLE
Protocol fee can potentially be burned

### ISSUE THREAD

**Issue by saxenism** [Gravita-Protocol/Gravita-SmartContracts#279]
# Protocol fee can potentially be burned

## Severity

High Severity

Reason: Theft or long term freezing of unclaimed yield or other assets

## Explanation

Let's assume that the correct `grvtStaking` address is `address(BEEF)`. So, when we get to the `FeeCollector.setAddress` function, we will pass `_grvtStakingAddress` as `address(BEEF)` and `_routeToGRVTStaking` as  `true`, and then the function will go through as expected. Here is the `setAddress` function for reference:
```solidity
	function setAddresses(
		address _borrowerOperationsAddress,
		address _vesselManagerAddress,
		address _grvtStakingAddress,
		address _debtTokenAddress,
		address _treasuryAddress,
		bool _routeToGRVTStaking
	) external initializer {
		require(_treasuryAddress != address(0));
		__Ownable_init();
		borrowerOperationsAddress = _borrowerOperationsAddress;
		vesselManagerAddress = _vesselManagerAddress;
		grvtStaking = IGRVTStaking(_grvtStakingAddress);
		debtTokenAddress = _debtTokenAddress;
		treasuryAddress = _treasuryAddress;
		routeToGRVTStaking = _routeToGRVTStaking;
		if (_routeToGRVTStaking && address(grvtStaking) == address(0)) {
			revert FeeCollector__InvalidGRVTStakingAddress();
		}
	}
```

However, if by mistake the `FeeCollector.setGRVTStakingAddress` is called with `address _grvtStakingAddress` being `address(0)`, then the final state of the contract would be:
`_routeToGRVTStaking` = `true`
`_grvtStakingAddress` = `address(0)`

Here is the `setGRVTStakingAddress` function for your reference:
```solidity
function setGRVTStakingAddress(address _grvtStakingAddress) external onlyOwner {
		grvtStaking = IGRVTStaking(_grvtStakingAddress);
		emit GRVTStakingAddressChanged(_grvtStakingAddress);
	}
```

With this state, if the `_collectFee` or `handleRedemptionFee` function is invoked, the entire amount would be sent to `address(0)`, effectively burning the protocol's revenue and resulting in a massive loss of funds.

## Recommended Mitigation Steps

Before making any transfer in the `_collectFee` and `handleRedemptionFee` functions make sure that the recipient is not `address(0)`.

**Comment by 0xfornax** [comment]
We appreciate the report. Checking for zero addresses would fall into the best practice critique category which is ineligible for the competition.
