### ISSUE TITLE
No proper check to whether vessel's debt is larger than the deposited debt in sp

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#283]
**Affected Smart contracts**
VesselManagerOperations.sol

**Impact**
If vessel debt is lesser than  Stability pool deposited debt token , it will send a fraction of the vessel's collateral to the Stability Pool leads to loss for liquidator.

**Severity**
medium  

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManagerOperations.sol#L878-L885

**Description :-**
The comments states in line [L878-L881](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManagerOperations.sol#L878-L881)
 If the vessel's debt is larger than the deposited debt token in the Stability Pool:
 - Offset an amount of the vessel's debt equal to the debt token in the Stability Pool
- Send a fraction of the vessel's collateral to the Stability Pool, equal to the fraction of its offset debt 

But there is no check to whether debt is larger than  SP deposited debt token . It will calculates the fractions to be send to Stability pool even if  the debt is lesser than SP deposited debt token leads to loss to Liquidator .

**Recommedation :-**

uint totalSPDepositedDebt = stabilityPool.getTotalDebtTokenDeposits()  ;

if ( _debt > totalSPDepositedDebt) {

collToSendToSP = _coll * debtToOffset / _debt;   // Fractions of collateral to be send SP
}

**Comment by 0xfornax** [comment]
We appreciate the submission. The function works as intended: the liquidator is always guaranteed the debtTokenGasCompensation (which was set aside on Vessel creation) and a percentage of the vessel's collateral before distributing the debt to the Stability Pool (see https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManagerOperations.sol#L204).
