### ISSUE TITLE
functions `BorrowerOperations._requireCallerIsBorrower(address)` and `BorrowerOperations._requireCallerIsStabilityPool()` are not used

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#286]
### Title

functions `BorrowerOperations._requireCallerIsBorrower(address)` and `BorrowerOperations._requireCallerIsStabilityPool()` are not used

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L557-L559

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L683-L685

### Recommendation

Functions should be removed because they are not used

**Comment by 0xfornax** [comment]
We appreciate the submission. The unused code was removed for gas savings.
