### ISSUE TITLE
Pausable ERC20 tokens might break project's functionality

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#287]
**Affected Smart contracts**
BorrowerOperations.sol
VesselManager.sol
VesselManagerOperations.sol

**Impact**
Loss to protocol and liquidator . 

**Severity**
Medium because collateral can paused .

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/BorrowerOperations.sol#L113

**Description :-**
According to Docs ' [Gravita enables users to borrow funds by using multiple forms of collateral, including LSTs.](https://docs.gravitaprotocol.com/gravita-docs/how-does-gravita-work/general#how-can-i-use-gravita) ' which accepts multiple forms of collateral 

Scenario :-
User opens vessel with (eg: BNB or other pausable tokens) as collateral . Then collateral value fall down than MICR , then liquidator try to call liquidate function at ,the same time supplied collateral has paused by Binance then loss to liquidator and Gravita protocol due to paused collateral cannot transfer to  liquidator .  

**Reference** 
View this tweet by binance about pausing the all user's BNB due to irregular activity . 
https://twitter.com/BNBCHAIN/status/1578148078636650496?lang=en

**Recommedation :-**
Implement new logic for working with pausable tokens . OR Disallow pausable  tokens .

**Comment by 0xfornax** [comment]
We appreciate the submission. The Gravita team will select which ERC20s will be onboarded on the protocol and, of course, only compatible tokens would be selected (we don't intend to support a series of token types - pausable, ERC777, rebasing, etc). Our launch list is WETH, rETH, WstETH and BLUSD.
