### ISSUE TITLE
Ignore the return value from the functions

### ISSUE THREAD

**Issue by karagyozovLT** [Gravita-Protocol/Gravita-SmartContracts#294]
### Title

Ignore the return value from the functions

### Affected smart contract

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L165

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/BorrowerOperations.sol#L166

https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5e45123d169a126a3055945373421e1bda5515b9/contracts/VesselManagerOperations.sol#L284

### Description

Ignore the return value from these functions `BorrowerOperations.contractsCache.vesselManager.increaseVesselColl` ,`BorrowerOperations.contractsCache.vesselManager.increaseVesselDebt` and `VesselManagerOperations.contractsCache.vesselManager.updateBaseRateFromRedemption`.

### Recommendation

Use the return value of these functions, or remove the return value from the function if you are not going to use them.

**Comment by 0xfornax** [comment]
Thank you for your submission. While we appreciate your interest in providing critiques of best practices, we would like to clarify that the rules state such submissions are not eligible.
