### ISSUE TITLE
VesselManager: `lastFeeOperationTime` is not modified correctly resulting in a much slower decay model for borrowing base rate

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#298]
In the `VesselManager._updateLastFeeOpTime` function, `lastFeeOperationTime` is not modified correctly. As a result, `updateBaseRateFromRedemption` will decay the base rate more slowly than expected (worst case half slower).

Since borrowing base rate is so fundamental to the protocol, this unexpected delay in decay leads to serious impact on Gravita protocol.

### Affected smart contract
- VesselManager
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/5281b2cd58cae941e688850f9bb19d707bb40aed/contracts/VesselManager.sol#L655-L662

### Description

These are the steps by which `updateBaseRateFromRedemption` will decay the base rate more slowly than expected because of the wrong modification of `lastFeeOperationTime` in `_updateLastFeeOpTime`:

```solidity
	function updateBaseRateFromRedemption(
		address _asset,
		uint256 _assetDrawn,
		uint256 _price,
		uint256 _totalDebtTokenSupply
	) external override onlyVesselManagerOperations returns (uint256) {
		uint256 decayedBaseRate = _calcDecayedBaseRate(_asset);
		uint256 redeemedDebtFraction = _assetDrawn * _price / _totalDebtTokenSupply;
		uint256 newBaseRate = decayedBaseRate + (redeemedDebtFraction / BETA);
		newBaseRate = GravitaMath._min(newBaseRate, DECIMAL_PRECISION);
		assert(newBaseRate > 0);
		baseRate[_asset] = newBaseRate;
		emit BaseRateUpdated(_asset, newBaseRate);
		_updateLastFeeOpTime(_asset);
		return newBaseRate;
	}

	function _updateLastFeeOpTime(address _asset) internal {
		uint256 timePassed = block.timestamp - lastFeeOperationTime[_asset];
		if (timePassed >= SECONDS_IN_ONE_MINUTE) {
			// Update the last fee operation time only if time passed >= decay interval. This prevents base rate griefing.
			lastFeeOperationTime[_asset] = block.timestamp;
			emit LastFeeOpTimeUpdated(_asset, block.timestamp);
		}
	}

	function _calcDecayedBaseRate(address _asset) internal view returns (uint256) {
		uint256 minutesPassed = _minutesPassedSinceLastFeeOp(_asset);
		uint256 decayFactor = GravitaMath._decPow(MINUTE_DECAY_FACTOR, minutesPassed);
		return baseRate[_asset] * decayFactor / DECIMAL_PRECISION;
	}

	function _minutesPassedSinceLastFeeOp(address _asset) internal view returns (uint256) {
		return (block.timestamp - lastFeeOperationTime[_asset]) / SECONDS_IN_ONE_MINUTE;
	}
```

1. `updateBaseRateFromRedemption` calls `_calcDecayedBaseRate` to calculate the decayed base rate based how many minutes elapsed since last recorded `lastFeeOperationTime` for a respective `_asset`.
2. `updateBaseRateFromRedemption` then calls `_updateLastFeeOpTime` to set `lastFeeOperationTime` to the current timestamp if at least 1 minute has passed.
3. The problem with such an update of `lastFeeOperationTime` is, if 1.999 minutes had passed, the base rate will only decay for 1 minute, at the same time, 1.999 minutes will be added on `lastFeeOperationTime`. In other words, in a worst scenario, for every 1.999 minutes, the base rate will only decay for 1 minute. Therefore, the base rate will decay more slowly then expected.
4. The borrowing base rate is very fundamental to the whole protocol. Any small deviation is accumulative. In the worse case, the decay speed will slow down by half.

### Recommendation

Consider using the effective elapsed time that is consumed by the model so far to revise the `lastFeeOperationTime` mapping.

```solidity
	function _updateLastFeeOpTime(address _asset) internal {
		uint256 timePassed = block.timestamp - lastFeeOperationTime[_asset];
		if (timePassed >= SECONDS_IN_ONE_MINUTE) {
			// Update the last fee operation time only if time passed >= decay interval. This prevents base rate griefing.
			lastFeeOperationTime[_asset] += _minutesPassedSinceLastFeeOp(_asset) * SECONDS_IN_ONE_MINUTE;
			emit LastFeeOpTimeUpdated(_asset, block.timestamp);
		}
	}
```

**Comment by 0xfornax** [comment]
Thank you for your report. While we appreciate your concern, we would like to clarify that the system is working as expected. The design choices for decaying fees are explained in detail in the following link: https://github.com/liquity/dev/#fee-decay-implementation.

**Comment by akshaysrivastav** [comment]
While the intention is to prevent griefing, the current implementations decays the base rate much slower than expected which is incorrect.

In a scenario where the function is executed every 1.99 minutes (119 seconds) for the next 1000 iterations, the actual time passed will be ~1983 minutes while the decay will only happen for 1000 minutes.

This makes decay to be 50% slower than expected. This clearly seems a bug.
@0xfornax

**Comment by 0xfornax** [comment]
> While the intention is to prevent griefing, the current implementations decays the base rate much slower than expected which is incorrect.

This is exactly the same decay rate implemented on other protocols and is the correct behavior.
