### ISSUE TITLE
The `_leftSumColls` function in **StabilityPool** it's used only in the tests

### ISSUE THREAD

**Issue by rotcivegaf** [Gravita-Protocol/Gravita-SmartContracts#317]
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/6f41018b0832ce6e1465fad5c0f8170f47febb3b/contracts/StabilityPool.sol#L864-L891

### Description

This function it's used only in the tests

### Recommendation

Move this one to the tests contract, Look: #316

**Comment by 0xfornax** [comment]
We appreciate the submission. We removed the function from the contract to save on the deployment gas.
