### ISSUE TITLE
Incomplete timelock mechanism implemented

### ISSUE THREAD

**Issue by akshaysrivastav** [Gravita-Protocol/Gravita-SmartContracts#323]
The timelock feature of Gravita protocol is incompletely implemented which can result in timelock mechanisms getting completely bypassed.

### Affected smart contract

- AdminContract
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/6f41018b0832ce6e1465fad5c0f8170f47febb3b/contracts/AdminContract.sol#L15

### Description

The Gravita protocol has introduced Timelock contract to maintain sufficient protocol decentralisation. The Timelock contract is used to introduce time delayed configuration changes in these contracts:
- PriceFeed
    - setOracle
- DebtToken
    - addWhitelist

The AdminContract inherits ProxyAdmin contract which contains `changeProxyAdmin`, `upgrade` and `upgradeAndCall` functions. With the help of these functions the `owner` of the AdminContract can upgrade the code of Proxy contracts instantly. The owner can also change the `proxyAdmin` of all Proxy contracts instantly. This instant upgrade/change defeats the entire purpose of using the Timelock contracts. 

Hence this leads to two issues:
- Insufficient timelock mechanism, as timelock can be bypassed by upgrading the contract directly.
- All Proxy contracts can be upgraded instantly.

I understand that in the [medium article](https://hatsfinance.medium.com/get-ready-for-a-new-audit-competition-coming-to-hats-finance-up-to-105k-in-prizes-8bbcf3d51034) centralization risk was marked out of scope by mentioning:
> “Centralization risks” that are known and/or explicitly coded into the protocol (e.g. an administrator can upgrade crucial contracts and steal all funds)

However this report is more inclined towards bypassing the timelocks completely which is definitely not an explicitly coded or intended scenario.

### Attack scenario
- DebtToken gets deployed behind a Proxy.
- The `DebtToken.addWhitelist` is a time delayed function.
- Instead of waiting for necessary time delay, the `owner` of `AdminContract` upgrades the `DebtToken` to a contract which doesn't need a time delay. Then calls the `DebtToken.addWhitelist` function instantly.
- Timelock got bypassed and `DebtToken.addWhitelist` function got called instantly. The impact of this can be more severe due the the issue reported in #313. 

Similar scenario is possible for `PriceFeed.setOracle` function.

### Recommendation

In AdminContract override the `changeProxyAdmin`, `upgrade` and `upgradeAndCall` functions and add the `shortTimelockOnly` or `longTimelockOnly` modifiers to them appropriately. This will make sure that the contracts cannot be upgraded instantly and time delays are enforced.

**Comment by akshaysrivastav** [comment]
PR - #327

**Comment by 0xfornax** [comment]
We appreciate the submission but the rules are clear that issues related to centralization risks are not eligible.

**Comment by akshaysrivastav** [comment]
The bug reported here is not an obvious centralization risk. The implementation of Timelocks in Gravita is intended to minimize the risk of sudden configuration changes to the protocol. But the report here clearly demonstrates how those timelocked limitations can be bypassed.

Quoting the guidelines here:
> “Centralization risks” that are known and/or explicitly coded into the protocol (e.g. an administrator can upgrade crucial contracts and steal all funds)
Attacks that require access to leaked private keys or trusted addresses

The reported issue neither seems to be known or explicitly coded. Hope you can reconsider this report @0xfornax.

**Comment by 0xfornax** [comment]
@akshaysrivastav you are spamming us with a large number of comments, while the rules EXPLICITLY mention this case as not eligible 
"Centralization risks” that are known and/or explicitly coded into the protocol (e.g. an **administrator can upgrade crucial contracts** and steal all funds)"
