### ISSUE TITLE
Gas Optimisation Report 

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#336]
Due to Limit in GitHub body(65553) characters only . I add gas report in GitHub Repo which contains the analytics of gas savings both Hardhat and RemixID. And already submited through on-chain also . 

Link :-
https://github.com/pavankv241/Gravita-gas-optimisation/blob/main/Gas%20Optimisation%20Report

**Comment by 0xfornax** [comment]
We appreciate the detailed report. This submission gets second place for the gas optimizations prize. Please reach out on Discord to provide your wallet address.
