### ISSUE TITLE
[ACE-01M] Incorrect Specification of Gap

### ISSUE THREAD

**Issue by 0xfornax** [Gravita-Protocol/Gravita-SmartContracts#374]
## ACE-01M: Incorrect Specification of Gap

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Standard Conformity](/appendix/finding-types#standard-conformity) | <img class="o-severity o-unknown" src="https://omniscia.io/report-assets/unknown.png" /> | [AddressesConfigurable.sol:L33](https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/ece280b7e6004612facc5a3dab04ca84cd1b0f29/contracts/Dependencies/AddressesConfigurable.sol#L33) |

### Description:

The referenced `_gap` variable is meant to indicate an OpenZeppelin like variable that reserves a gap during compilation for future upgrades of the contract that may wish to utilize storage slots.

The methodology it is calculated is non-standard within the Gravita Protocol repository.

### Impact:

While proper upgrades would not result in an error, the non-standard way to calculate the array's size currently employed can lead to significant data corruption if the `length` is improperly updated in a consequent logic update.

### Example:

```solidity
uint256[47] private __gap;
```

### Recommendation:

We advise the `length` of the array to be calculated by subtracting the total number of storage slots reserved by the contract **currently** from the value of `50`.

In the current instance, this would yield us `33` as the contract reserves `17` storage slots.

**Comment by spider-g** [comment]
Acknowledged and done, __gap was set to 33 on AddressesConfigurable.sol.
